<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>Transfer Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #4f46e5;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        th {
            background-color: #4f46e5;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        @media print {
            body { margin: 0; }
            @page { 
                margin: 1cm; 
                size: A4;
            }
            .no-print { display: none !important; }
            .print-button { display: none !important; }
        }
        .print-button {
            position: fixed;
            top: 20px;
            right: 20px;
            background: #4f46e5;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
        .print-button:hover {
            background: #3730a3;
        }
    </style>
</head>
<body>
    <button class="print-button no-print" onclick="window.print()">🖨️ Print</button>
    <div class="header">
        <h1>Transfer Report</h1>
        <p>Generated on {{ date('Y-m-d H:i:s') }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Reference</th>
                <th>From Warehouse</th>
                <th>To Warehouse</th>
                <th>Items</th>
                <th>Status</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $transfer)
            <tr>
                <td>{{ $transfer->date }}</td>
                <td>{{ $transfer->reference }}</td>
                <td>{{ $transfer->from_wh }}</td>
                <td>{{ $transfer->to_wh }}</td>
                <td>{{ number_format($transfer->items, 2) }}</td>
                <td>{{ ucfirst($transfer->statut) }}</td>
                <td>{{ $transfer->category }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($data) }} | Generated by Inventory System</p>
    </div>
    
    <script>
        // Auto-print when page loads - multiple approaches for better compatibility
        let printAttempted = false;
        
        function attemptPrint() {
            if (printAttempted) return;
            printAttempted = true;
            
            try {
                window.print();
            } catch (e) {
                console.log('Print failed:', e);
            }
        }
        
        // Try immediate print first
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(attemptPrint, 500);
        });
        
        // Fallback for window.onload
        window.onload = function() {
            setTimeout(attemptPrint, 1000);
        };
        
        // Additional fallback for older browsers
        window.addEventListener('load', function() {
            setTimeout(attemptPrint, 1500);
        });
        
        // Force print on any user interaction (click, keypress, etc.)
        document.addEventListener('click', function() {
            attemptPrint();
        });
        
        document.addEventListener('keydown', function() {
            attemptPrint();
        });
        
        // Try print immediately when script loads
        setTimeout(attemptPrint, 100);
    </script>
</body>
</html>